Yoon-jae/team02_week4

src/main/java/team02_week4/bill/AppView.java
src/main/java/team02_week4/bill/Calculator.java

Appview안에 메소드 추가됨.
Calculator.java 클래스 중복으로 인해 제거함.

AppView 내용 추가 및 Calculator.java제거

---

src/main/java/team02_week4/bill/Gold.java
src/main/java/team02_week4/bill/Silver.java

Gold, Silver클래스 구현.
필드 값 설정과 각 필드마다 set 메소드 구현.

Gold, Silver클래스 구현

---

src/main/java/team02_week4/bill/Line.java

Line 클래스의 세 가지의 필드 구현
usedMinutes
phoneNumber
lineUserName
세 가지 구현

Line 클래스 필드 구현

---

src/main/java/com/bill/team02/week4/Line.java
src/main/java/com/bill/team02_week4/Line.java

디폴트 생성자, 세개의 필드값을 지정 할 수 있는 생성자,
설정자 접근자 구현.

	Line 클래스 메소드와 생성자 구현

---

src/main/java/com/bill/team02/week4/AppController.java
src/main/java/com/bill/team02/week4/ClientAccountData.java
src/main/java/com/bill/team02/week4/FormController.java

clientAccountData, appController, FormController등 변경구현

accountData를 받는 과정 구현

---

src/main/java/com/bill/team02/week4/AppController.java
src/main/java/com/bill/team02/week4/ClientAccountData.java
src/main/java/com/bill/team02/week4/FormController.java

AppController, ClientAccountData, FormController

---

src/main/java/com/bill/team02/week4/ClientAccountData.java
src/main/java/com/bill/team02/week4/FormController.java
src/main/java/com/bill/team02/week4/Line.java

ClientAccountData, FormController, Line오류 수정 및 추가 구현

ClientAccountData, FormController, Line 추가구현

---

src/main/java/com/bill/team02/week4/ClientAccountData.java
target/.gitignore

Fix magic number issue
Fix tab characters issue
Fix Syntax issue

Fixed some issues

---

src/main/java/com/bill/team02/week4/ClientAccountData.java

private final to private final staitc

fixed constant var issue

---

src/main/java/com/bill/team02/week4/ClientAccountData.java

ClientAccountData merge conflict resolved

Conflict resolved

---

src/main/java/com/bill/team02/week4/ClientAccountData.java

All tabs replaced to space

---

src/main/java/com/bill/team02/week4/AppController.java
src/main/java/com/bill/team02/week4/ClientAccountData.java
src/main/java/com/bill/team02/week4/FormController.java
src/main/java/com/bill/team02/week4/Gold.java
src/main/java/com/bill/team02/week4/Plan.java
src/main/java/com/bill/team02/week4/RateCalculation.java
src/main/java/com/bill/team02/week4/Silver.java

output수정으로 인한 추가구현
plan name을 받아오는 등의 메소드 추가

output수정으로 인한 추가구현 및 수정

---

input.txt
src/main/java/com/bill/team02/week4/Plan.java

modify duplicated blocks error

---

src/main/java/com/bill/team02/week4/Gold.java
src/main/java/com/bill/team02/week4/Plan.java
src/main/java/com/bill/team02/week4/Silver.java

Plan Gold Silver 클래스 변경
Duplicate 오류 해결하기위함

solve the duplicated error

---

src/main/java/com/bill/team02/week4/ClientAccountData.java
src/main/java/com/bill/team02/week4/FormController.java

ClientAccountData의 calculateRate메소드 지역변수를 전역변수로 변경 및 여러 메소드 추가

output 출력 수정으로 인한 코드 수정

---

src/main/java/com/bill/team02/week4/ClientAccountData.java
src/main/java/com/bill/team02/week4/FormController.java

print문 추가와, getter 설정, checkFamilyDiscountAndPrint()메소드 구현

output 최종 수정을 위한 메소드 구현

---

src/main/java/com/bill/team02/week4/AppController.java
src/main/java/com/bill/team02/week4/ClientAccountData.java
src/main/java/com/bill/team02/week4/RateCalculation.java

Appcontroller Exception Issue fixed

---

src/main/java/com/bill/team02/week4/AppController.java
src/main/java/com/bill/team02/week4/IORuntimeException.java

IORuntimeException class added.

Exception issue fixed

---

src/main/java/com/bill/team02/week4/IORuntimeException.java
src/main/java/com/bill/team02/week4/Main.java

Magic number issue fixed

---

src/main/java/com/bill/team02/week4/AppController.java
src/main/java/com/bill/team02/week4/IORuntimeException.java

Exception issue fixed 2

---

src/main/java/com/bill/team02/week4/AppController.java

exception issue fixed 3

---

src/main/java/com/bill/team02/week4/AppController.java

Logger static issue fixed

---

src/main/java/com/bill/team02/week4/FormController.java

logger issue fixed

---

src/main/java/com/bill/team02/week4/FormController.java

log issue fixed

---

src/main/java/com/bill/team02/week4/AppController.java

err issue fixed

---

src/test/java/com/bill/team02/week4/UnitTest.java

unit test class 수정

---

src/main/java/com/bill/team02/week4/Main.java
src/test/java/com/bill/team02/week4/AppTest.java
src/test/java/com/bill/team02/week4/UnitTest.java

main의 다른 메소드 실행

---

src/test/java/com/bill/team02/week4/RateCalculationTest.java

Typing error fixed

---

src/test/java/com/bill/team02/week4/AppTest.java

Yet trying to increase coverage

AppTest modified. 

---

src/main/java/com/bill/team02/week4/Main.java
src/test/java/com/bill/team02/week4/AppTest.java

Trying to increase coverage

---

src/test/java/com/bill/team02/week4/AppTest.java

Merge conflict error fixed

---

pom.xml

plugin setting changed

---

src/test/java/com/bill/team02/week4/RateCalculationTest.java

class name changed

---

src/test/java/com/bill/team02/week4/SilverTest.java
src/test/java/com/bill/team02/week4/UnitTest.java

slivertest작성

---

src/test/java/com/bill/team02/week4/GoldTest.java

GoldClass Test created

---

src/test/java/com/bill/team02/week4/FormControllerTest.java
src/test/java/com/bill/team02/week4/SilverTest.java

silverTest클래스와 FormControllerTest클래스 작성

unit test를 위한 클래스 작성

---

src/main/java/com/bill/team02/week4/AppController.java
src/main/java/com/bill/team02/week4/FormController.java
src/test/java/com/bill/team02/week4/AppControllerTest.java
src/test/java/com/bill/team02/week4/AppViewTest.java
src/test/java/com/bill/team02/week4/ClientAccountDataTest.java
src/test/java/com/bill/team02/week4/GoldTest.java
src/test/java/com/bill/team02/week4/PlanTest.java
src/test/java/com/bill/team02/week4/SilverTest.java

Completely implemented test : gold, silver, plan, line, ratecalculation, appcontroller
Need to implement : AppViewTest, FormControllerTest, ClientAccountDataTest

Test classes implementing

---

src/main/java/com/bill/team02/week4/Main.java

import junit deleted
